//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: buffcommand.proto
// Note: requires additional types generated from: common.proto
// Note: requires additional types generated from: savedata.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Buff")]
  public partial class Buff : global::ProtoBuf.IExtensible
  {
    public Buff() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddBuffBuffUserCmd_S", Value=1)]
      AddBuffBuffUserCmd_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddBuffListBuffUserCmd_S", Value=2)]
      AddBuffListBuffUserCmd_S = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveBuffBuffUserCmd_CS", Value=3)]
      RemoveBuffBuffUserCmd_CS = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddBuffBuffUserCmd_S")]
  public partial class AddBuffBuffUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddBuffBuffUserCmd_S() {}
    
    private Cmd.SaveBuff _buff;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SaveBuff buff
    {
      get { return _buff; }
      set { _buff = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddBuffListBuffUserCmd_S")]
  public partial class AddBuffListBuffUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddBuffListBuffUserCmd_S() {}
    
    private readonly global::System.Collections.Generic.List<Cmd.SaveBuff> _bufflist = new global::System.Collections.Generic.List<Cmd.SaveBuff>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bufflist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SaveBuff> bufflist
    {
      get { return _bufflist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveBuffBuffUserCmd_CS")]
  public partial class RemoveBuffBuffUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public RemoveBuffBuffUserCmd_CS() {}
    
    private uint _thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BuffAddType")]
    public enum BuffAddType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuffAddType_None", Value=0)]
      BuffAddType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuffAddType_Replace", Value=1)]
      BuffAddType_Replace = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuffAddType_Time", Value=2)]
      BuffAddType_Time = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuffAddType_All", Value=3)]
      BuffAddType_All = 3
    }
  
}