//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"Command")]
    public enum Command
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Select", Value=2)]
      Select = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat", Value=3)]
      Chat = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Map", Value=4)]
      Map = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Move", Value=5)]
      Move = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Data", Value=6)]
      Data = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Property", Value=7)]
      Property = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Skill", Value=8)]
      Skill = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Buff", Value=9)]
      Buff = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Quest", Value=10)]
      Quest = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Item", Value=11)]
      Item = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Script", Value=12)]
      Script = 12
    }
  
}