//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Command.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"Command")]
    public enum Command
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Null", Value=0)]
      Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=1)]
      Login = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Select", Value=2)]
      Select = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat", Value=3)]
      Chat = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Map", Value=4)]
      Map = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Move", Value=5)]
      Move = 5
    }
  
}