//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pos")]
  public partial class Pos : global::ProtoBuf.IExtensible
  {
    public Pos() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemLocation")]
  public partial class ItemLocation : global::ProtoBuf.IExtensible
  {
    public ItemLocation() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private Cmd.ItemLocation.PackageType _type = Cmd.ItemLocation.PackageType.Main;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.ItemLocation.PackageType.Main)]
    public Cmd.ItemLocation.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PackageType")]
    public enum PackageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Main", Value=0)]
      Main = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Equip", Value=1)]
      Equip = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainUserData")]
  public partial class MainUserData : global::ProtoBuf.IExtensible
  {
    public MainUserData() {}
    
    private Cmd.MapUserData _userdata;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.MapUserData userdata
    {
      get { return _userdata; }
      set { _userdata = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _sp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    private long _exp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private long _nextexp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"nextexp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nextexp
    {
      get { return _nextexp; }
      set { _nextexp = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _pDam = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pDam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pDam
    {
      get { return _pDam; }
      set { _pDam = value; }
    }
    private int _mDam = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mDam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mDam
    {
      get { return _mDam; }
      set { _mDam = value; }
    }
    private int _pDef = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pDef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pDef
    {
      get { return _pDef; }
      set { _pDef = value; }
    }
    private int _mDef = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"mDef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mDef
    {
      get { return _mDef; }
      set { _mDef = value; }
    }
    private int _pIggnore = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pIggnore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pIggnore
    {
      get { return _pIggnore; }
      set { _pIggnore = value; }
    }
    private int _mIggnore = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mIggnore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mIggnore
    {
      get { return _mIggnore; }
      set { _mIggnore = value; }
    }
    private int _moveSpeed = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private int _attackSpeed = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"attackSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attackSpeed
    {
      get { return _attackSpeed; }
      set { _attackSpeed = value; }
    }
    private int _hit = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private int _hide = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"hide", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hide
    {
      get { return _hide; }
      set { _hide = value; }
    }
    private int _lucky = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"lucky", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lucky
    {
      get { return _lucky; }
      set { _lucky = value; }
    }
    private int _force = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"force", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int force
    {
      get { return _force; }
      set { _force = value; }
    }
    private int _miss = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"miss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int miss
    {
      get { return _miss; }
      set { _miss = value; }
    }
    private int _reflect = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"reflect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reflect
    {
      get { return _reflect; }
      set { _reflect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapUserData")]
  public partial class MapUserData : global::ProtoBuf.IExtensible
  {
    public MapUserData() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private string _charname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private bool _sexman;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sexman", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sexman
    {
      get { return _sexman; }
      set { _sexman = value; }
    }
    private Cmd.Profession _profession;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.Profession profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private int _movespeed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"movespeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int movespeed
    {
      get { return _movespeed; }
      set { _movespeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SceneEntryUid")]
  public partial class SceneEntryUid : global::ProtoBuf.IExtensible
  {
    public SceneEntryUid() {}
    
    private Cmd.SceneEntryType _entrytype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entrytype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.SceneEntryType entrytype
    {
      get { return _entrytype; }
      set { _entrytype = value; }
    }
    private ulong _entryid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"entryid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong entryid
    {
      get { return _entryid; }
      set { _entryid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipPos")]
    public enum EquipPos
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Weapon", Value=1)]
      Weapon = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bracer", Value=2)]
      Bracer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Clothe", Value=3)]
      Clothe = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Pants", Value=4)]
      Pants = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Necklace", Value=5)]
      Necklace = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ring", Value=6)]
      Ring = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Shoes", Value=7)]
      Shoes = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Profession")]
    public enum Profession
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_ZhanShi", Value=1)]
      Profession_ZhanShi = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_DaoShi", Value=2)]
      Profession_DaoShi = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_FaShi", Value=3)]
      Profession_FaShi = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneEntryType")]
    public enum SceneEntryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryType_Player", Value=0)]
      SceneEntryType_Player = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryType_Npc", Value=1)]
      SceneEntryType_Npc = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryType_Item", Value=2)]
      SceneEntryType_Item = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneEntryState")]
    public enum SceneEntryState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Normal", Value=0)]
      SceneEntryState_Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Dead", Value=1)]
      SceneEntryState_Dead = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Hide", Value=2)]
      SceneEntryState_Hide = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NpcBaseType")]
    public enum NpcBaseType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcBaseType_None", Value=0)]
      NpcBaseType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcBaseType_Monster", Value=1)]
      NpcBaseType_Monster = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcBaseType_Elite", Value=2)]
      NpcBaseType_Elite = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcBaseType_Boss", Value=3)]
      NpcBaseType_Boss = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcBaseType_Box", Value=4)]
      NpcBaseType_Box = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NpcClickType")]
    public enum NpcClickType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcClickType_None", Value=0)]
      NpcClickType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcClickType_Homeland", Value=1)]
      NpcClickType_Homeland = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcClickType_FriendCountry", Value=2)]
      NpcClickType_FriendCountry = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcClickType_OtherCountry", Value=4)]
      NpcClickType_OtherCountry = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TileType")]
    public enum TileType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TileType_None", Value=0)]
      TileType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TileType_Walk", Value=1)]
      TileType_Walk = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TileType_Water", Value=2)]
      TileType_Water = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"QuestProcess")]
    public enum QuestProcess
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestProcess_None", Value=0)]
      QuestProcess_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestProcess_Doing", Value=1)]
      QuestProcess_Doing = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestProcess_CanDone", Value=2)]
      QuestProcess_CanDone = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestProcess_Done", Value=3)]
      QuestProcess_Done = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestProcess_Max", Value=4)]
      QuestProcess_Max = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CopySceneType")]
    public enum CopySceneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopySceneType_None", Value=0)]
      CopySceneType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopySceneType_Normal", Value=1)]
      CopySceneType_Normal = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CountryId")]
    public enum CountryId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CountryId_Middle", Value=100)]
      CountryId_Middle = 100
    }
  
}