//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pos")]
  public partial class Pos : global::ProtoBuf.IExtensible
  {
    public Pos() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemLocation")]
  public partial class ItemLocation : global::ProtoBuf.IExtensible
  {
    public ItemLocation() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private Cmd.ItemLocation.PackageType _type = Cmd.ItemLocation.PackageType.Main;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.ItemLocation.PackageType.Main)]
    public Cmd.ItemLocation.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PackageType")]
    public enum PackageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Main", Value=0)]
      Main = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Equip", Value=1)]
      Equip = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainUserData")]
  public partial class MainUserData : global::ProtoBuf.IExtensible
  {
    public MainUserData() {}
    
    private Cmd.MapUserData _userdata;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.MapUserData userdata
    {
      get { return _userdata; }
      set { _userdata = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _sp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    private long _exp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapUserData")]
  public partial class MapUserData : global::ProtoBuf.IExtensible
  {
    public MapUserData() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private string _charname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private bool _sexman;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sexman", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sexman
    {
      get { return _sexman; }
      set { _sexman = value; }
    }
    private Cmd.Profession _profession;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.Profession profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SceneEntryUid")]
  public partial class SceneEntryUid : global::ProtoBuf.IExtensible
  {
    public SceneEntryUid() {}
    
    private Cmd.SceneEntryType _entrytype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entrytype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.SceneEntryType entrytype
    {
      get { return _entrytype; }
      set { _entrytype = value; }
    }
    private ulong _entryid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"entryid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong entryid
    {
      get { return _entryid; }
      set { _entryid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipPos")]
    public enum EquipPos
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Weapon", Value=1)]
      Weapon = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bracer", Value=2)]
      Bracer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Clothe", Value=3)]
      Clothe = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Pants", Value=4)]
      Pants = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Necklace", Value=5)]
      Necklace = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ring", Value=6)]
      Ring = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Shoes", Value=7)]
      Shoes = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Profession")]
    public enum Profession
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_ZhanShi", Value=1)]
      Profession_ZhanShi = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_DaoShi", Value=2)]
      Profession_DaoShi = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_FaShi", Value=3)]
      Profession_FaShi = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneEntryType")]
    public enum SceneEntryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryType_Player", Value=0)]
      SceneEntryType_Player = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryType_Npc", Value=1)]
      SceneEntryType_Npc = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryType_Item", Value=2)]
      SceneEntryType_Item = 2
    }
  
}