//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pos")]
  public partial class Pos : global::ProtoBuf.IExtensible
  {
    public Pos() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Profession")]
    public enum Profession
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_ZhanShi", Value=1)]
      Profession_ZhanShi = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_DaoShi", Value=2)]
      Profession_DaoShi = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Profession_FaShi", Value=3)]
      Profession_FaShi = 3
    }
  
}