//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common/config/Config.proto
namespace Cmd.Config
{
    [global::ProtoBuf.ProtoContract(Name=@"Version")]
    public enum Version
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=2014)]
      Login = 2014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Game", Value=2014)]
      Game = 2014
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Debug")]
    public enum Debug
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"All", Value=1)]
      All = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Whj", Value=1)]
      Whj = 1
    }
  
}