//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Config.proto
namespace Pmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Config")]
  public partial class Config : global::ProtoBuf.IExtensible
  {
    public Config() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Version")]
    public enum Version
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Version_Login", Value=2015)]
      Version_Login = 2015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Version_Game", Value=2014)]
      Version_Game = 2014
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Debug")]
    public enum Debug
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Debug_All", Value=1)]
      Debug_All = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Debug_Whj", Value=1)]
      Debug_Whj = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}