//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DataCommand.proto
// Note: requires additional types generated from: Common.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Data")]
  public partial class Data : global::ProtoBuf.IExtensible
  {
    public Data() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MainUserDataUserCmd_S", Value=1)]
      MainUserDataUserCmd_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetUserHpDataUserCmd_S", Value=2)]
      SetUserHpDataUserCmd_S = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetUserSpDataUserCmd_S", Value=3)]
      SetUserSpDataUserCmd_S = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetUserHpSpDataUserCmd_S", Value=4)]
      SetUserHpSpDataUserCmd_S = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainUserDataUserCmd_S")]
  public partial class MainUserDataUserCmd_S : global::ProtoBuf.IExtensible
  {
    public MainUserDataUserCmd_S() {}
    
    private Cmd.MainUserData _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.MainUserData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetUserHpDataUserCmd_S")]
  public partial class SetUserHpDataUserCmd_S : global::ProtoBuf.IExtensible
  {
    public SetUserHpDataUserCmd_S() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private int _curhp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"curhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curhp
    {
      get { return _curhp; }
      set { _curhp = value; }
    }
    private int _prehp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prehp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int prehp
    {
      get { return _prehp; }
      set { _prehp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetUserSpDataUserCmd_S")]
  public partial class SetUserSpDataUserCmd_S : global::ProtoBuf.IExtensible
  {
    public SetUserSpDataUserCmd_S() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private int _cursp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cursp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cursp
    {
      get { return _cursp; }
      set { _cursp = value; }
    }
    private int _presp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"presp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int presp
    {
      get { return _presp; }
      set { _presp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetUserHpSpDataUserCmd_S")]
  public partial class SetUserHpSpDataUserCmd_S : global::ProtoBuf.IExtensible
  {
    public SetUserHpSpDataUserCmd_S() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _maxhp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }
    private int _sp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    private int _maxsp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maxsp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxsp
    {
      get { return _maxsp; }
      set { _maxsp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}