//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common/Login.proto
namespace Cmd.Login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSGTYPE")]
  public partial class MSGTYPE : global::ProtoBuf.IExtensible
  {
    public MSGTYPE() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"VersionVerify", Value=1)]
      VersionVerify = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VersionVerifyResult", Value=2)]
      VersionVerifyResult = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WebGateUserRequestLogon", Value=3)]
      WebGateUserRequestLogon = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HttpsUserRequestLogon", Value=4)]
      HttpsUserRequestLogon = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HttpsUserReturnLogon", Value=5)]
      HttpsUserReturnLogon = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VersionVerify")]
  public partial class VersionVerify : global::ProtoBuf.IExtensible
  {
    public VersionVerify() {}
    
    private string _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VersionVerifyResult")]
  public partial class VersionVerifyResult : global::ProtoBuf.IExtensible
  {
    public VersionVerifyResult() {}
    
    private bool _ok;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ok", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ok
    {
      get { return _ok; }
      set { _ok = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WebGateUserRequestLogon")]
  public partial class WebGateUserRequestLogon : global::ProtoBuf.IExtensible
  {
    public WebGateUserRequestLogon() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _net_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"net_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int net_type
    {
      get { return _net_type; }
      set { _net_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HttpsUserRequestLogon")]
  public partial class HttpsUserRequestLogon : global::ProtoBuf.IExtensible
  {
    public HttpsUserRequestLogon() {}
    
    private string _loginstr;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loginstr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string loginstr
    {
      get { return _loginstr; }
      set { _loginstr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HttpsUserReturnLogon")]
  public partial class HttpsUserReturnLogon : global::ProtoBuf.IExtensible
  {
    public HttpsUserReturnLogon() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}