//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MapCommand.proto
// Note: requires additional types generated from: Common.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Map")]
  public partial class Map : global::ProtoBuf.IExtensible
  {
    public Map() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"InitMainUserDataMapUserCmd_S", Value=1)]
      InitMainUserDataMapUserCmd_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddMapUserDataAndPosMapUserCmd_S", Value=2)]
      AddMapUserDataAndPosMapUserCmd_S = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveMapUserMapUserCmd_S", Value=3)]
      RemoveMapUserMapUserCmd_S = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddMapNpcDataAndPosMapUserCmd_S", Value=4)]
      AddMapNpcDataAndPosMapUserCmd_S = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveMapNpcMapUserCmd_S", Value=5)]
      RemoveMapNpcMapUserCmd_S = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MainUserIntoSceneMapUserCmd_S", Value=6)]
      MainUserIntoSceneMapUserCmd_S = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserLevelUpMapUserCmd_S", Value=7)]
      UserLevelUpMapUserCmd_S = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitMainUserDataMapUserCmd_S")]
  public partial class InitMainUserDataMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public InitMainUserDataMapUserCmd_S() {}
    
    private Cmd.MainUserData _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.MainUserData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private uint _homeland;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"homeland", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint homeland
    {
      get { return _homeland; }
      set { _homeland = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddMapUserDataAndPosMapUserCmd_S")]
  public partial class AddMapUserDataAndPosMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddMapUserDataAndPosMapUserCmd_S() {}
    
    private Cmd.MapUserData _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.MapUserData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private uint _homeland;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"homeland", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint homeland
    {
      get { return _homeland; }
      set { _homeland = value; }
    }
    private Cmd.Pos _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.Pos pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveMapUserMapUserCmd_S")]
  public partial class RemoveMapUserMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public RemoveMapUserMapUserCmd_S() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapNpcData")]
  public partial class MapNpcData : global::ProtoBuf.IExtensible
  {
    public MapNpcData() {}
    
    private ulong _tempid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _maxhp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddMapNpcDataAndPosMapUserCmd_S")]
  public partial class AddMapNpcDataAndPosMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddMapNpcDataAndPosMapUserCmd_S() {}
    
    private uint _baseid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private Cmd.MapNpcData _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.MapNpcData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private Cmd.Pos _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.Pos pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveMapNpcMapUserCmd_S")]
  public partial class RemoveMapNpcMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public RemoveMapNpcMapUserCmd_S() {}
    
    private ulong _tempid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainUserIntoSceneMapUserCmd_S")]
  public partial class MainUserIntoSceneMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public MainUserIntoSceneMapUserCmd_S() {}
    
    private uint _countryid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"countryid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint countryid
    {
      get { return _countryid; }
      set { _countryid = value; }
    }
    private uint _mapid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private Cmd.Pos _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.Pos pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserLevelUpMapUserCmd_S")]
  public partial class UserLevelUpMapUserCmd_S : global::ProtoBuf.IExtensible
  {
    public UserLevelUpMapUserCmd_S() {}
    
    private ulong _charid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}