//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NullCommand.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Null")]
  public partial class Null : global::ProtoBuf.IExtensible
  {
    public Null() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ForwardNullUserCmd_CS", Value=0)]
      ForwardNullUserCmd_CS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TickRequestNullUserCmd_CS", Value=1)]
      TickRequestNullUserCmd_CS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TickReturnNullUserCmd_CS", Value=2)]
      TickReturnNullUserCmd_CS = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForwardNullUserCmd_CS")]
  public partial class ForwardNullUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public ForwardNullUserCmd_CS() {}
    
    private uint _byCmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"byCmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint byCmd
    {
      get { return _byCmd; }
      set { _byCmd = value; }
    }
    private uint _byParam;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"byParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint byParam
    {
      get { return _byParam; }
      set { _byParam = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private ulong _fid = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fid
    {
      get { return _fid; }
      set { _fid = value; }
    }
    private readonly global::System.Collections.Generic.List<byte[]> _data = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(5, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TickRequestNullUserCmd_CS")]
  public partial class TickRequestNullUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public TickRequestNullUserCmd_CS() {}
    
    private uint _requesttime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requesttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requesttime
    {
      get { return _requesttime; }
      set { _requesttime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TickReturnNullUserCmd_CS")]
  public partial class TickReturnNullUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public TickReturnNullUserCmd_CS() {}
    
    private uint _requesttime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requesttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requesttime
    {
      get { return _requesttime; }
      set { _requesttime = value; }
    }
    private uint _mytime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mytime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mytime
    {
      get { return _mytime; }
      set { _mytime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}