//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nullcommand.proto
namespace Pmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Null")]
  public partial class Null : global::ProtoBuf.IExtensible
  {
    public Null() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ForwardNullUserPmd_CS", Value=0)]
      ForwardNullUserPmd_CS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TickRequestNullUserPmd_CS", Value=1)]
      TickRequestNullUserPmd_CS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TickReturnNullUserPmd_CS", Value=2)]
      TickReturnNullUserPmd_CS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestCloseNullUserPmd_CS", Value=3)]
      RequestCloseNullUserPmd_CS = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForwardNullUserPmd_CS")]
  public partial class ForwardNullUserPmd_CS : global::ProtoBuf.IExtensible
  {
    public ForwardNullUserPmd_CS() {}
    
    private uint _byCmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"byCmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint byCmd
    {
      get { return _byCmd; }
      set { _byCmd = value; }
    }
    private uint _byParam;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"byParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint byParam
    {
      get { return _byParam; }
      set { _byParam = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private ulong _fid = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fid
    {
      get { return _fid; }
      set { _fid = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private ulong _prototype = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"prototype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong prototype
    {
      get { return _prototype; }
      set { _prototype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TickRequestNullUserPmd_CS")]
  public partial class TickRequestNullUserPmd_CS : global::ProtoBuf.IExtensible
  {
    public TickRequestNullUserPmd_CS() {}
    
    private uint _requesttime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requesttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requesttime
    {
      get { return _requesttime; }
      set { _requesttime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TickReturnNullUserPmd_CS")]
  public partial class TickReturnNullUserPmd_CS : global::ProtoBuf.IExtensible
  {
    public TickReturnNullUserPmd_CS() {}
    
    private uint _requesttime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requesttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requesttime
    {
      get { return _requesttime; }
      set { _requesttime = value; }
    }
    private uint _mytime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mytime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mytime
    {
      get { return _mytime; }
      set { _mytime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCloseNullUserPmd_CS")]
  public partial class RequestCloseNullUserPmd_CS : global::ProtoBuf.IExtensible
  {
    public RequestCloseNullUserPmd_CS() {}
    
    private string _reason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}