//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Pmd.proto
namespace Pmd
{
    [global::ProtoBuf.ProtoContract(Name=@"PlatCommand")]
    public enum PlatCommand
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=250)]
      Login = 250
    }
  
}