//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: QuestCommand.proto
// Note: requires additional types generated from: Common.proto
// Note: requires additional types generated from: SaveData.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quest")]
  public partial class Quest : global::ProtoBuf.IExtensible
  {
    public Quest() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddQuestTraceQuestUserCmd_S", Value=1)]
      AddQuestTraceQuestUserCmd_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQeustStateQuestUserCmd_S", Value=3)]
      RefreshQeustStateQuestUserCmd_S = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveQuestQuestUserCmd_CS", Value=4)]
      RemoveQuestQuestUserCmd_CS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAcceptQuestQuestUserCmd_C", Value=5)]
      RequestAcceptQuestQuestUserCmd_C = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishQuestQuestUserCmd_C", Value=6)]
      RequestFinishQuestQuestUserCmd_C = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestClickQuestTraceQuestUserCmd_C", Value=7)]
      RequestClickQuestTraceQuestUserCmd_C = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnClickQuestTraceQuestUserCmd_S", Value=8)]
      ReturnClickQuestTraceQuestUserCmd_S = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestQuestDescQuestUserCmd_C", Value=9)]
      RequestQuestDescQuestUserCmd_C = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnQuestDetailInfoQuestUserCmd_S", Value=10)]
      ReturnQuestDetailInfoQuestUserCmd_S = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestTrace")]
  public partial class QuestTrace : global::ProtoBuf.IExtensible
  {
    public QuestTrace() {}
    
    private Cmd.SaveQuest _squest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"squest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SaveQuest squest
    {
      get { return _squest; }
      set { _squest = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddQuestTraceQuestUserCmd_S")]
  public partial class AddQuestTraceQuestUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddQuestTraceQuestUserCmd_S() {}
    
    private Cmd.QuestTrace _quest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"quest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.QuestTrace quest
    {
      get { return _quest; }
      set { _quest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshQeustStateQuestUserCmd_S")]
  public partial class RefreshQeustStateQuestUserCmd_S : global::ProtoBuf.IExtensible
  {
    public RefreshQeustStateQuestUserCmd_S() {}
    
    private Cmd.SaveQuest _squest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"squest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SaveQuest squest
    {
      get { return _squest; }
      set { _squest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveQuestQuestUserCmd_CS")]
  public partial class RemoveQuestQuestUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public RemoveQuestQuestUserCmd_CS() {}
    
    private uint _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestAcceptQuestQuestUserCmd_C")]
  public partial class RequestAcceptQuestQuestUserCmd_C : global::ProtoBuf.IExtensible
  {
    public RequestAcceptQuestQuestUserCmd_C() {}
    
    private uint _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private ulong _npctempid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"npctempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong npctempid
    {
      get { return _npctempid; }
      set { _npctempid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestFinishQuestQuestUserCmd_C")]
  public partial class RequestFinishQuestQuestUserCmd_C : global::ProtoBuf.IExtensible
  {
    public RequestFinishQuestQuestUserCmd_C() {}
    
    private uint _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private ulong _npctempid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"npctempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong npctempid
    {
      get { return _npctempid; }
      set { _npctempid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestClickQuestTraceQuestUserCmd_C")]
  public partial class RequestClickQuestTraceQuestUserCmd_C : global::ProtoBuf.IExtensible
  {
    public RequestClickQuestTraceQuestUserCmd_C() {}
    
    private uint _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private ulong _npctempid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"npctempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong npctempid
    {
      get { return _npctempid; }
      set { _npctempid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldPosition")]
  public partial class WorldPosition : global::ProtoBuf.IExtensible
  {
    public WorldPosition() {}
    
    private Cmd.Pos _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Pos pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private uint _countryid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"countryid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint countryid
    {
      get { return _countryid; }
      set { _countryid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReturnClickQuestTraceQuestUserCmd_S")]
  public partial class ReturnClickQuestTraceQuestUserCmd_S : global::ProtoBuf.IExtensible
  {
    public ReturnClickQuestTraceQuestUserCmd_S() {}
    
    private uint _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private Cmd.ClickQuestTaceEvent _event;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"event", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.ClickQuestTaceEvent @event
    {
      get { return _event; }
      set { _event = value; }
    }
    private Cmd.WorldPosition _position = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.WorldPosition position
    {
      get { return _position; }
      set { _position = value; }
    }
    private uint _npcbaseid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"npcbaseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint npcbaseid
    {
      get { return _npcbaseid; }
      set { _npcbaseid = value; }
    }
    private string _dialogname = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dialogname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dialogname
    {
      get { return _dialogname; }
      set { _dialogname = value; }
    }
    private bool _repeatclick = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"repeatclick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool repeatclick
    {
      get { return _repeatclick; }
      set { _repeatclick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestQuestDescQuestUserCmd_C")]
  public partial class RequestQuestDescQuestUserCmd_C : global::ProtoBuf.IExtensible
  {
    public RequestQuestDescQuestUserCmd_C() {}
    
    private uint _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReturnQuestDetailInfoQuestUserCmd_S")]
  public partial class ReturnQuestDetailInfoQuestUserCmd_S : global::ProtoBuf.IExtensible
  {
    public ReturnQuestDetailInfoQuestUserCmd_S() {}
    
    private Cmd.SaveQuest _squest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"squest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SaveQuest squest
    {
      get { return _squest; }
      set { _squest = value; }
    }
    private Cmd.QuestProcess _process;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.QuestProcess process
    {
      get { return _process; }
      set { _process = value; }
    }
    private uint _npcbaseid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"npcbaseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint npcbaseid
    {
      get { return _npcbaseid; }
      set { _npcbaseid = value; }
    }
    private string _detail;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string detail
    {
      get { return _detail; }
      set { _detail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClickQuestTaceEvent")]
    public enum ClickQuestTaceEvent
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClickQuestTaceEvent_None", Value=0)]
      ClickQuestTaceEvent_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClickQuestTaceEvent_GoToNpc", Value=1)]
      ClickQuestTaceEvent_GoToNpc = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClickQuestTaceEvent_GoToPositon", Value=2)]
      ClickQuestTaceEvent_GoToPositon = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClickQuestTaceEvent_OpenDialog", Value=3)]
      ClickQuestTaceEvent_OpenDialog = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClickQuestTaceEvent_AttackMonster", Value=4)]
      ClickQuestTaceEvent_AttackMonster = 4
    }
  
}