//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ScriptCommand.proto
// Note: requires additional types generated from: Common.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Script")]
  public partial class Script : global::ProtoBuf.IExtensible
  {
    public Script() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectSceneEntryScriptUserCmd_CS", Value=1)]
      SelectSceneEntryScriptUserCmd_CS = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectSceneEntryScriptUserCmd_CS")]
  public partial class SelectSceneEntryScriptUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public SelectSceneEntryScriptUserCmd_CS() {}
    
    private Cmd.SceneEntryUid _entry;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SceneEntryUid entry
    {
      get { return _entry; }
      set { _entry = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}