//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillCommand.proto
// Note: requires additional types generated from: Common.proto
// Note: requires additional types generated from: SaveData.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddSkillSkillUserCmd_S", Value=1)]
      AddSkillSkillUserCmd_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddSkillListSkillUserCmd_S", Value=2)]
      AddSkillListSkillUserCmd_S = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveSkillSkillUserCmd_CS", Value=3)]
      RemoveSkillSkillUserCmd_CS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LearnSkillSkillUserCmd_C", Value=4)]
      LearnSkillSkillUserCmd_C = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddSkillSkillUserCmd_S")]
  public partial class AddSkillSkillUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddSkillSkillUserCmd_S() {}
    
    private Cmd.SaveSkill _skill;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SaveSkill skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddSkillListSkillUserCmd_S")]
  public partial class AddSkillListSkillUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddSkillListSkillUserCmd_S() {}
    
    private readonly global::System.Collections.Generic.List<Cmd.SaveSkill> _skilllist = new global::System.Collections.Generic.List<Cmd.SaveSkill>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skilllist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SaveSkill> skilllist
    {
      get { return _skilllist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveSkillSkillUserCmd_CS")]
  public partial class RemoveSkillSkillUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public RemoveSkillSkillUserCmd_CS() {}
    
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LearnSkillSkillUserCmd_C")]
  public partial class LearnSkillSkillUserCmd_C : global::ProtoBuf.IExtensible
  {
    public LearnSkillSkillUserCmd_C() {}
    
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}