//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillCommand.proto
// Note: requires additional types generated from: Common.proto
// Note: requires additional types generated from: SaveData.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"Param")]
    public enum Param
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddSkillSkillUserCmd_S", Value=1)]
      AddSkillSkillUserCmd_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddSkillListSkillUserCmd_S", Value=2)]
      AddSkillListSkillUserCmd_S = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveSkillSkillUserCmd_CS", Value=3)]
      RemoveSkillSkillUserCmd_CS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LearnSkillSkillUserCmd_C", Value=4)]
      LearnSkillSkillUserCmd_C = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestUseSkillUserCmd_C", Value=5)]
      RequestUseSkillUserCmd_C = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnUseSkillUserCmd_S", Value=6)]
      ReturnUseSkillUserCmd_S = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddSkillSkillUserCmd_S")]
  public partial class AddSkillSkillUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddSkillSkillUserCmd_S() {}
    
    private Cmd.SaveSkill _skill;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SaveSkill skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddSkillListSkillUserCmd_S")]
  public partial class AddSkillListSkillUserCmd_S : global::ProtoBuf.IExtensible
  {
    public AddSkillListSkillUserCmd_S() {}
    
    private readonly global::System.Collections.Generic.List<Cmd.SaveSkill> _skilllist = new global::System.Collections.Generic.List<Cmd.SaveSkill>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skilllist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SaveSkill> skilllist
    {
      get { return _skilllist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveSkillSkillUserCmd_CS")]
  public partial class RemoveSkillSkillUserCmd_CS : global::ProtoBuf.IExtensible
  {
    public RemoveSkillSkillUserCmd_CS() {}
    
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LearnSkillSkillUserCmd_C")]
  public partial class LearnSkillSkillUserCmd_C : global::ProtoBuf.IExtensible
  {
    public LearnSkillSkillUserCmd_C() {}
    
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestUseSkillUserCmd_C")]
  public partial class RequestUseSkillUserCmd_C : global::ProtoBuf.IExtensible
  {
    public RequestUseSkillUserCmd_C() {}
    
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.SceneEntryUid> _hurts = new global::System.Collections.Generic.List<Cmd.SceneEntryUid>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hurts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SceneEntryUid> hurts
    {
      get { return _hurts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillHurtData")]
  public partial class SkillHurtData : global::ProtoBuf.IExtensible
  {
    public SkillHurtData() {}
    
    private Cmd.SceneEntryUid _hurtid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hurtid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SceneEntryUid hurtid
    {
      get { return _hurtid; }
      set { _hurtid = value; }
    }
    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReturnUseSkillUserCmd_S")]
  public partial class ReturnUseSkillUserCmd_S : global::ProtoBuf.IExtensible
  {
    public ReturnUseSkillUserCmd_S() {}
    
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private Cmd.SceneEntryUid _owner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.SceneEntryUid owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.SkillHurtData> _hurts = new global::System.Collections.Generic.List<Cmd.SkillHurtData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"hurts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.SkillHurtData> hurts
    {
      get { return _hurts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}