//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: observable (OnPropertyChanged) enabled
    
// Generated from: Assets/Scripts/Config/UserData.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserData")]
  public partial class UserData : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public UserData() {}
    
    private readonly global::System.Collections.Generic.List<uint> _skillbar = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skillbar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> skillbar
    {
      get { return _skillbar; }
    }
  
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}