//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TableItem.proto
namespace table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableItemItem")]
  public partial class TableItemItem : global::ProtoBuf.IExtensible
  {
    public TableItemItem() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _icons;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"icons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint icons
    {
      get { return _icons; }
      set { _icons = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _color;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }
    private uint _flag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private table.TableItemItem.robnumItem _robnum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"robnum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public table.TableItemItem.robnumItem robnum
    {
      get { return _robnum; }
      set { _robnum = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"robnumItem")]
  public partial class robnumItem : global::ProtoBuf.IExtensible
  {
    public robnumItem() {}
    
    private uint _minnum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"minnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint minnum
    {
      get { return _minnum; }
      set { _minnum = value; }
    }
    private uint _maxnum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxnum
    {
      get { return _maxnum; }
      set { _maxnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}