//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TableMap.proto
namespace table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableMap")]
  public partial class TableMap : global::ProtoBuf.IExtensible
  {
    public TableMap() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _mapfile;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mapfile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapfile
    {
      get { return _mapfile; }
      set { _mapfile = value; }
    }
    private string _minimapfile;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"minimapfile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string minimapfile
    {
      get { return _minimapfile; }
      set { _minimapfile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}