//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TableRoleLevel.proto
namespace table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableRoleLevelItem")]
  public partial class TableRoleLevelItem : global::ProtoBuf.IExtensible
  {
    public TableRoleLevelItem() {}
    
    private uint _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _maxHp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}