//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TableSkill.proto
namespace table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableSkill")]
  public partial class TableSkill : global::ProtoBuf.IExtensible
  {
    public TableSkill() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private float _radius;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private uint _profession;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _requirePoint;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"requirePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requirePoint
    {
      get { return _requirePoint; }
      set { _requirePoint = value; }
    }
    private uint _requireType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"requireType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requireType
    {
      get { return _requireType; }
      set { _requireType = value; }
    }
    private uint _requireLevel;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"requireLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requireLevel
    {
      get { return _requireLevel; }
      set { _requireLevel = value; }
    }
    private uint _requireSkill;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"requireSkill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requireSkill
    {
      get { return _requireSkill; }
      set { _requireSkill = value; }
    }
    private uint _requireSkillLevel;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"requireSkillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint requireSkillLevel
    {
      get { return _requireSkillLevel; }
      set { _requireSkillLevel = value; }
    }
    private uint _cd;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cd
    {
      get { return _cd; }
      set { _cd = value; }
    }
    private uint _prepareTime;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"prepareTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prepareTime
    {
      get { return _prepareTime; }
      set { _prepareTime = value; }
    }
    private bool _interruptable;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"interruptable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool interruptable
    {
      get { return _interruptable; }
      set { _interruptable = value; }
    }
    private string _path;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}