//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TableLevel.proto
namespace table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableLevelItem")]
  public partial class TableLevelItem : global::ProtoBuf.IExtensible
  {
    public TableLevelItem() {}
    
    private uint _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _mapHP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapHP
    {
      get { return _mapHP; }
      set { _mapHP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}