//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Config/MapNav.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapNav")]
  public partial class MapNav : global::ProtoBuf.IExtensible
  {
    public MapNav() {}
    
    private uint _gridxnum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gridxnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gridxnum
    {
      get { return _gridxnum; }
      set { _gridxnum = value; }
    }
    private uint _gridznum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gridznum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gridznum
    {
      get { return _gridznum; }
      set { _gridznum = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _grids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"grids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> grids
    {
      get { return _grids; }
    }
  
    private float _gridwidth = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gridwidth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float gridwidth
    {
      get { return _gridwidth; }
      set { _gridwidth = value; }
    }
    private float _gridheight = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gridheight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float gridheight
    {
      get { return _gridheight; }
      set { _gridheight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}